[
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*---MENUS---*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/herr.jpg", url: "herr", nombre: "Opciones"},
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/nacionales.jpg", url: "nacionales", nombre: "Nacionales" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/infantiles.jpg", url: "infantiles", nombre: "Infantiles" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/variados.jpg", url: "variados", nombre: "Variados" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/premium.jpg", url: "premium", nombre: "Cinemas" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/deportes.jpg", url: "deportes", nombre: "Deportes" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/247.jpg", url: "247", nombre: "24/7" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/movievariado.jpg", url: "movievariado", nombre: "YTB Variado" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/moviewestern.jpg", url: "moviewestern", nombre: "YTB Western" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/movieanime.jpg", url: "movieanime", nombre: "YTB Anime" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/moviefamiliar.jpg", url: "moviefamiliar", nombre: "YTB Familiar" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/moviehorror.jpg", url: "moviehorror", nombre: "YTB Horror" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/moviewar.jpg", url: "moviewar", nombre: "YTB Wars" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/movieacomedia.jpg", url: "moviecomedia", nombre: "YTB Comedia" },
    { tipo: "menu", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/musica.jpg", url: "musica", nombre: "Musicales" },
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*---OPCIONES---*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    { tipo: "herr", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/activar.jpg", nombre: "Activar", url: "https://tv.teleclub.xyz/activar"  },
    { tipo: "herr", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/actualizar.jpg", nombre: "Actualizar", url: "/actualizar"  },
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*---NACIONALES---*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/tcs.jpg", nombre: "TCS +", url: "https://telecorporacion.cdn.vustreams.com/live/19b307cf-3f2d-44cb-bce6-0fd65365c56a/live.isml/live.m3u8" },
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/canal2.jpg", nombre: "Camal 2", url: "https://telecorporacion-es.cdn.vustreams.com/live/d3e259fa-736d-46b0-b1c9-71caf946ace9/live.isml/d3e259fa-736d-46b0-b1c9-71caf946ace9.m3u8" },
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/canal3.jpg", nombre: "Camal 3", url: "https://cloud2.streaminglivehd.com:1936/8048/8048/playlist.m3u8" },
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/canal4.jpg", nombre: "Camal 4", url: "https://streaming.asamblea.gob.sv/hls/plenariahd.m3u8" },
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/canal5.jpg", nombre: "Camal 5", url: "https://cdn.elsalvadordigital.com:1936/wowtv/smil:wowtv.smil/playlist.m3u8" },
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/canal6.jpg", nombre: "Camal 6", url: "https://telecorporacion.cdn.vustreams.com/live/b164ebe7-decf-4a5a-8aea-5bb56fb92dfc/live.isml/live.m3u8" },
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/canal9.jpg", nombre: "Camal 9", url: "https://streaming.asamblea.gob.sv/hls/plenariahd.m3u8" },
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/canal11.jpg", nombre: "Camal 11", url: "https://stream.giostreaming.net:19360/canal11/canal11.m3u8" },
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/canal12.jpg", nombre: "Camal 12", url: "https://alba-sv-c12-c12.stream.mediatiquestream.com/index.m3u8" },
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/canal19.jpg", nombre: "Camal 19", url: "https://mgv-channel19.akamaized.net/hls/live/2093190/MGV_CHANNEL19/master.m3u8" },
    { tipo: "nacionales", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/canal21.jpg", nombre: "Camal 21", url: "https://mgv-channel21.akamaized.net/hls/live/2093191/MGV_CHANNEL21/master.m3u8" },
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*---MOVIEWESTERN---*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/porunosdolares.jpg", url: "22LUQT2MuXk.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elbuenoelmaloyelfeo.jpg", url: "NXVSV4UKz-4.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elultimopistolero.jpg", url: "IZ_vtx3kC4s.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lavenganzadefrankjames.jpg", url: "_emI0fhXszw.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/barroenlosojos.jpg", url: "Q_yYNKUwTc8.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/unmalditoamanecer.jpg", url: "-UoUvcu5lGk.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lamuertenocuentalosdolares.jpg", url: "5FA2MXpUMWw.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lasombradesartana.jpg", url: "ycW9U9eQ5Rs.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/masalladelaley.jpg", url: "Uq0ChAeYO5w.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/django.jpg", url: "PJoIQcBl4QU.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/regresoacasadeunvaquero.jpg", url: "fSJmNgkCqks.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/unhombreuncaballounapistola.jpg", url: "GyoMx-kkWaw.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/los4defortapache.jpg", url: "QhtmoKK44FQ.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/unagujeroenlafrente.jpg", url: "p2xqPYogeIw.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/justiciacalibre45.jpg", url: "DzUvg9y5Hac.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lellamabantrinidad.jpg", url: "ChzXUUU76lg.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/leseguianllamandotrinidad.jpg", url: "fMMOFkqGj_0.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elhombredeladiligencia.jpg", url: "Ez8_j6DDzlQ.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/unvaqueromuertonoesunvaquero.jpg", url: "raRR1C_YF-8.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/ringovuelveparamatar.jpg", url: "e_nxEk1G9Kg.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/dueloenelbarro.jpg", url: "CCGYDkerli0.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/123disparaestavez.jpg", url: "F7Y2sqi_GXM.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/laleydelahorca.jpg", url: "jCvCYtlZ49E.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/kidblue.jpg", url: "ImGL5OyNVJI.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/eljugador.jpg", url: "c_D4pH73BaE.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/danzaconlobos.jpg", url: "WGx8LvOsSQ0.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/latumba.jpg", url: "VnpWsNNS0Z4.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/KirkDouglasOeste.jpg", url: "coIuejnBxFg.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/aliadosimprobables.jpg", url: "5YeeIcHEJTo.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elsheriftraidor.jpg", url: "G40EhRUBYQQ.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/sinperdon.jpg", url: "aDIZcOSdnfc.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/perrossucios.jpg", url: "EE1DNIQ6-go.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/puedesamigo.jpg", url: "iwQIz7_5oOk.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/fueradetiempo.jpg", url: "qlnIqcw-7Sc.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/trinidadysartana.jpg", url: "Ej9TvNhZbwk.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/ahorcado.jpg", url: "EkcZ96_G254.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/tuverdugo.jpg", url: "bh801UK-kv8.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/sangreenlatierra.jpg", url: "1vS_tBbqnIk.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/unacoltenlamanodeldiablo.jpg", url: "4pgIObGuCrY.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/quiengritavenganza.jpg", url: "MfKAyo-.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/legendbillielnino.jpg", url: "V56eP9G6698.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/sagitario.jpg", url: "Y4TuwWW7lRo.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/westernpeligroso.jpg", url: "3LCZsuQ1Dc0.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/westbrother.jpg", url: "9jGSejS0mak.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/padremurai.jpg", url: "ySHHK11NRzg.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/riomaldito.jpg", url: "3JgPlDGg4RQ.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/colinadebotas.jpg", url: "UAFo-RkQM3o.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elborde.jpg", url: "4sVl6R42v54.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lagranja.jpg", url: "FRK3_OkTyqs.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/otroladodeley.jpg", url: "fiKg-4XSR3g.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/apachekid.jpg", url: "A1d2ew6Y-d0.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elvengador.jpg", url: "HZnHCu2i6Cc.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/fiebredepradera.jpg", url: "cLpWouaOx8k.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/frankyjessi.jpg", url: "XrC-6BTNjhM.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/malditoinvierno.jpg", url: "-UoUvcu5lGk.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/duelomortal.jpg", url: "cjPkpjqXPN0.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/sinaliento.jpg", url: "Me_J3c2VSdA.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/oromaldito.jpg", url: "4cgD60meH88.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/loquieromuerto.jpg", url: "L3CMFyAJP1Y.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/rapidoylamuerte.jpg", url: "eL2Zj_ODvIE.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/venganzaeneloeste.jpg", url: "2sebynsktco.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/eltesorodejessijames.jpg", url: "kDlAI0cScAk.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/mannaja.jpg", url: "TAixK1I7zUc.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/shriftmandibula.jpg", url: "aDmW2gJWlKs.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/atravesdelhuracan.jpg", url: "5BPyw9UJvAQ.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/dinamitajoe.jpg", url: "tQHKf6zXUlM.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/eltirador.jpg", url: "fH1VGUSS4Ec.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/weslegend.jpg", url: "z8xorTxs8vo.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/historia2pistolas.jpg", url: "ZEeUfXQ-O8Q.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/balasthobs.jpg", url: "rg-0MJlSFMk.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/vidadepistolero.jpg", url: "3akhgwkg9aM.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/sinley.jpg", url: "mXdgzs9TZQ4.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/llanerosol.jpg", url: "i05brRClB5k.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/5forajidos.jpg", url: "nxWSy1UbLRs.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/batalladeearp.jpg", url: "Ockz1-Eg1uA.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/killerkid.jpg", url: "HgjWsQ2ZXnM.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/alambradadeviolencia.jpg", url: "TFagDpmF4yQ.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/sentencia.jpg", url: "w-IszlzEfZo.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/rewcazador.jpg", url: "s9qpHI2U4yo.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/granmclint.jpg", url: "kMoZ8YqyIag.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/hickok.jpg", url: "wydC2NxmXA0.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/pistolamaldita.jpg", url: "BvMfVBdIxc4.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/diezhorcas.jpg", url: "kDzifV2oe4c.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/cazadordedemonios.jpg", url: "bje4lTTXVRM.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/rifledeken.jpg", url: "m6FYVLjaazU.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/fronteradelsur.jpg", url: "m72vUx_K92A.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/djangovssartana.jpg", url: "vgdzl-N7vs0.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/filadecruces.jpg", url: "x1Q3D7ju2bI.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/venganzaindia.jpg", url: "kwLzgVTG1ik.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lasjusticieras.jpg", url: "mYFfJKBJNU4.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/vidacriminal.jpg", url: "Q8pIrvjEsDU.ytb" },
    { tipo: "moviewestern", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/reveldearizona.jpg", url: "HbOUTU-7Xbg.ytb" },
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*---MOVIEWAR---*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/unionbound.jpg", url: "23vSIMEyJs4.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/warsrace.jpg", url: "6CxBeAXQiYs.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/invencible.jpg", url: "GB38cgAaAVw.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/ultimaaccion.jpg", url: "RMSLbKTzbGw.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/santosysoldados.jpg", url: "J9G9YmMOcvA.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/sinretorno.jpg", url: "M47p7rUuOHQ.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/masayadelafrontera.jpg", url: "9Wygy3Fr6aQ.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/guerrabrutal.jpg", url: "6ARShw9Y8g8.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/misionnormandia.jpg", url: "lWJggDnV-Vs.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/laprimeralinea.jpg", url: "JT6yGDDp-f8.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/batallaxlibertad.jpg", url: "aDzuEtOt9NM.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/guerradeinvierno.jpg", url: "2_vhGWJvkNo.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/soysara.jpg", url: "T4nvl1iPzzk.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/brotherinwars.jpg", url: "RrFiCFSlQOw.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elturista.jpg", url: "4OgHMJzFLF0.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/tiemposdeoscuridad.jpg", url: "c5WQBhsp7fc.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/zonadeguerra.jpg", url: "Jya839LUhaQ.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/operacionrescate.jpg", url: "tUgoLnJ5R4E.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/golpeamericano.jpg", url: "tDqdFRgRHSY.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/alavista.jpg", url: "DFbiQfxT4vU.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lealtad.jpg", url: "ZWaHIRMFpJY.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/sacrificiofinal.jpg", url: "ttzynHVaE4s.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/5diasdeguerra.jpg", url: "j8BgyiUqSSU.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/1914frenteoccidental.jpg", url: "PB4D5yFN2dg.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/1989sv.jpg", url: "RHwooe3nFCE.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/vocesinocentes.jpg", url: "hQy453pK5bk.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/sobreviviendoguazapa.jpg", url: "OTk8oLXJNiM.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/almasdehierro.jpg", url: "qytWjSC8e0o.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/soldierboy.jpg", url: "PEwsnrTiNCU.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/holocausto.jpg", url: "hA8nQShZ7MA.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/operacionnaziabajo.jpg", url: "-kVjYCiE-a0.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/escapedeauschwitz.jpg", url: "C1a3CLcDgUk.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/masdellimite.jpg", url: "0oRIpy7pGU4.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/entramosalamanecer.jpg", url: "VmeW9o0nEug.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/aladoenemigo.jpg", url: "H6n1RIML19Q.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/hamptonlegion.jpg", url: "SI_bhTqYb5M.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/36horasdeguerra.jpg", url: "CGGkEQ0YomA.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/ultimoataqhitler.jpg", url: "ZBGYdJSU6Eg.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/stalingrado.jpg", url: "dzOZSaJPo-c.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lagranguerra.jpg", url: "p9q8jkZd4vI.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/batallalingrado.jpg", url: "TIeCTzFhanI.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/rojosonazis.jpg", url: "39a_fwyyZOw.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lobosj.jpg", url: "jKMeLFGMVDQ.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/fuimosheroes.jpg", url: "Eyp9xekwjUM.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/traslineaenemiga3.jpg", url: "X6bLBIlIrZs.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/deciciondehonor.jpg", url: "vbyjaZbqc4s.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lalegion.jpg", url: "fGRYHGCMx_Q.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/fantasmasdeguerra.jpg", url: "bjUt6ALO4JM.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/talibans.jpg", url: "AUri0KULgHk.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/hiroshima.jpg", url: "5JbdrAVLvS8.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/ultimotrenauschwitz.jpg", url: "2yZUplpZ0xY.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/guardiadeauschwitz.jpg", url: "VvHdig2bMXw.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/diariodeanafrank.jpg", url: "zBV2uN8Zcjg.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/profpersa.jpg", url: "Gd674X9fqtQ.ytb" },
    { tipo: "moviewar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/angeldeauschwitz.jpg", url: "POHpohU0sGg.ytb" },
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*---MOVIEFAMILIAR---*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/masalladeltiempo.jpg", url: "JmYo0Pvo4rA.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lenyelperro.jpg", url: "itUzTS-j4B4.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/caballocampeon.jpg", url: "sOvojtQKivg.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/atrapandoelsueño.jpg", url: "K5hiC5uc31o.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/jinetesconespiritu.jpg", url: "LdOm7MrIGkg.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/famav.jpg", url: "I-AvQoU6meo.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/aldiablolove.jpg", url: "f1lZWZsjHMg.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elviselcerdo.jpg", url: "zM5Bh34QxIM.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/sueñodehope.jpg", url: "PZITHoTqeqU.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/legadodehope.jpg", url: "a2Eg3aACp8g.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/princesaypony.jpg", url: "sFHA27C2Hg4.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/inviernodehoro.jpg", url: "lyxw6uuGygY.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/12perrosdenavidad.jpg", url: "GiV2LJu7lao.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/navidadpara2.jpg", url: "UWKYriniaYk.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/waldisneymagico.jpg", url: "bgqyGXvMuj4.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/perrodelcielo.jpg", url: "ifxXypfIWDQ.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/intrusodenavidad.jpg", url: "DX65HDouP28.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/navidadtraviesa.jpg", url: "hUI2hjJovHg.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/antesdetiempo.jpg", url: "oz-nfxnqObc.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elnovato.jpg", url: "GnGVKHK6oJg.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/caminoalibertad.jpg", url: "QETBu1K2Gmk.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/comoserrey.jpg", url: "8la5tezxN64.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/navidadmilagrosa.jpg", url: "ou93m68M-Xs.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elelfo.jpg", url: "UFAvcVuwexI.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/deseodenavidad.jpg", url: "yDmlpOQdNcM.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/uncuentodenavidad.jpg", url: "_EF3037Evic.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/cuentodenavidad.jpg", url: "wr6DSr-4Wuc.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lamisiondesanta.jpg", url: "rZzHNxX0vAs.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/pandilladesanta.jpg", url: "dLDs45P0_D0.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/amorporcontrato.jpg", url: "cX5Y1xTZx3M.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/labellayelmalo.jpg", url: "zMsoH7dsSu0.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elplacercompania.jpg", url: "_rXyz3njNTw.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/laricapobre.jpg", url: "fk0S025UhE8.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/herenciadeamor.jpg", url: "YX2VK2HD2V0.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/cuandoloshijosregresan.jpg", url: "oDZuUp6bkLM.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/cuandoloshijosregresan.jpg", url: "oDZuUp6bkLM.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/tialocademy.jpg", url: "f8cnlrYD3VY.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/perfectosdesconocidos.jpg", url: "0-NdsaETJug.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/peqdetectives.jpg", url: "_nTw52VumXA.ytb" },
    { tipo: "moviefamiliar", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/escueladelavida.jpg", url: "eJE4d4fDp6s.ytb" },
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*---MOVIECOMEDIA---*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    { tipo: "moviecomedia", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/lacocinademelisa.jpg", url: "k8zo3-3obNw.ytb" },
    { tipo: "moviecomedia", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/matildap.jpg", url: "LnrtigFK63c.ytb" },
    { tipo: "moviecomedia", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/womenvsman.jpg", url: "PgC8t9koy-U.ytb" },
    { tipo: "moviecomedia", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/launi.jpg", url: "anB8rWWQtWE.ytb" },
    { tipo: "moviecomedia", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/40mas.jpg", url: "iCClkuzitv0.ytb" },
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*---MOVIEANIME---*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/planetadeltesoro.jpg", url: "qGtY_O5ioUE.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/birdslikeus.jpg", url: "347kxf8pGzA.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/rikibuscacuerno.jpg", url: "qtsde0Fodtc.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/dbzsuperbroly.jpg", url: "YcNIFi9ocNM.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/inuyasha1.jpg", url: "AN2NhRHHtpo.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/inuyasha2.jpg", url: "YH7I80xznyY.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/inuyasha3.jpg", url: "GiT2gX3f7h8.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/bleach2.jpg", url: "kQMxFzwdsV4.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/bleach4.jpg", url: "L2E4ELz_AkI.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/vampirehunter.jpg", url: "D_J-nr6GcFY.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/blame.jpg", url: "oafUsF4LqfA.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/dantesinferno.jpg", url: "OelibyLx6jM.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/narutoninjaroad.jpg", url: "FzRH5Iaa8Uc.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/narutoprisiondesangre.jpg", url: "SCYlPNUTaOc.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/onepiecegold.jpg", url: "h2oFTsH64EM.ytb" },
    { tipo: "movieanime", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/redline.jpg", url: "nQH47RD25Gc.ytb" },
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*---MOVIEVARIADO---*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    { tipo: "movievariado", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/amoryfrijoles.jpg", url: "UOx6guR1v54.ytb" },
    { tipo: "movievariado", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/reinoprohibido.jpg", url: "2aESi-d6ino.ytb" },
    { tipo: "movievariado", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/realidadacelerada.jpg", url: "DexVJ5x8cj8.ytb" },
    { tipo: "movievariado", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/camelotdragon.jpg", url: "R4dJm8OsonY.ytb" },
    { tipo: "movievariado", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/askeladden.jpg", url: "XjKltO4dsRY.ytb" },
    { tipo: "movievariado", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/faunuland.jpg", url: "EYF09C7wsmc.ytb" },
    { tipo: "movievariado", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/aveturefantasy.jpg", url: "Ec_zUC3g94g.ytb" },
    { tipo: "movievariado", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/elquintoelemento.jpg", url: "6AqNScn5Cq4.ytb" },
    { tipo: "movievariado", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/princesademarte.jpg", url: "5-tRv2i3G2g.ytb" },
    { tipo: "movievariado", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/laninasinmagia.jpg", url: "ShyUTIx7_hE.ytb" },
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*---TELECLUB---*/
    /*--------------------------------------------------------------------------------------------------------*/
    /*--------------------------------------------------------------------------------------------------------*/
    { name: "beinsportsextran", logo: "https://img.teleclub.xyz/beinsportsn.png", tipo: "deportes", nombre: "Bein Sports Extra Ñ", url: "http://tv.teleclub.xyz/stream/server_2/deportes/beinsportsextran/master.m3u8" },
    { name: "directvsports", logo: "https://img.teleclub.xyz/directvsports.png", tipo: "deportes", nombre: "Directv Sports", url: "http://tv.teleclub.xyz/stream/server_2/deportes/directvsports/master.m3u8" },
    { name: "directvsportsplus", logo: "https://img.teleclub.xyz/directvsports.png", tipo: "deportes", nombre: "Directv Sports +", url: "http://tv.teleclub.xyz/stream/server_2/deportes/directvsportsplus/master.m3u8" },
    { name: "directvsports2", logo: "https://img.teleclub.xyz/directvsports2.png", tipo: "deportes", nombre: "Directv Sports 2", url: "http://tv.teleclub.xyz/stream/server_2/deportes/directvsports2/master.m3u8" },
    { name: "espn1", logo: "https://img.teleclub.xyz/espn.png", tipo: "deportes", nombre: "ESPN 1", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espn1/master.m3u8" },
    { name: "espn2", logo: "https://img.teleclub.xyz/espn2.png", tipo: "deportes", nombre: "ESPN 2", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espn2/master.m3u8" },
    { name: "espn3", logo: "https://img.teleclub.xyz/espn3.png", tipo: "deportes", nombre: "ESPN 3", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espn3/master.m3u8" },
    { name: "espn4", logo: "https://img.teleclub.xyz/espn4.png", tipo: "deportes", nombre: "ESPN 4", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espn4/master.m3u8" },
    { name: "espn5", logo: "https://img.teleclub.xyz/espn.png", tipo: "deportes", nombre: "ESPN 5", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espn5/master.m3u8" },
    { name: "espnpremium", logo: "https://img.teleclub.xyz/espnpremium.png", tipo: "deportes", nombre: "ESPN Premium", url: "http://tv.teleclub.xyz/stream/server_2/deportes/espnpremium/master.m3u8" },
    { name: "foxsports1", logo: "https://img.teleclub.xyz/foxsports.png", tipo: "deportes", nombre: "Fox Sports 1", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports1/master.m3u8" },
    { name: "foxsports1mx", logo: "https://img.teleclub.xyz/foxsports.png", tipo: "deportes", nombre: "Fox Sports 1 MX", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports1mx/master.m3u8" },
    { name: "foxsports2", logo: "https://img.teleclub.xyz/foxsports2.png", tipo: "deportes", nombre: "Fox Sports 2", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports2/master.m3u8" },
    { name: "foxsports2mx", logo: "https://img.teleclub.xyz/foxsports2.png", tipo: "deportes", nombre: "Fox Sports 2 MX", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports2mx/master.m3u8" },
    { name: "foxsports2mx", logo: "https://img.teleclub.xyz/foxsports2.png", tipo: "deportes", nombre: "Fox Sports 2 MX", url: "http://tv.teleclub.xyz/stream/server_3/deportes/foxsports2mx/master.m3u8" },
    { name: "foxsports3", logo: "https://img.teleclub.xyz/foxsports3.png", tipo: "deportes", nombre: "Fox Sports 3", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports3/master.m3u8" },
    { name: "foxsports3mx", logo: "https://img.teleclub.xyz/foxsports3.png", tipo: "deportes", nombre: "Fox Sports 3 MX", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsports3mx/master.m3u8" },
    { name: "foxsportspremiummx", logo: "https://img.teleclub.xyz/foxsportspremium.png", tipo: "deportes", nombre: "Fox Sports Premium MX", url: "http://tv.teleclub.xyz/stream/server_2/deportes/foxsportspremiummx/master.m3u8" },
    { name: "golperu", logo: "https://img.teleclub.xyz/golperu.png", tipo: "deportes", nombre: "Gol Peru", url: "http://tv.teleclub.xyz/stream/server_2/deportes/golperu/master.m3u8" },
    { name: "goltv", logo: "https://img.teleclub.xyz/goltv.png", tipo: "deportes", nombre: "Gol TV", url: "http://tv.teleclub.xyz/stream/server_2/deportes/goltv/master.m3u8" },
    { name: "nbatv", logo: "https://img.teleclub.xyz/nba.png", tipo: "deportes", nombre: "NBA TV", url: "http://tv.teleclub.xyz/stream/server_2/deportes/nbatv/master.m3u8" },
    { name: "tntsports", logo: "https://img.teleclub.xyz/tntsports.png", tipo: "deportes", nombre: "TNT Sports", url: "http://tv.teleclub.xyz/stream/server_2/deportes/tntsports/master.m3u8" },
    { name: "tudn", logo: "https://img.teleclub.xyz/tudn.png", tipo: "deportes", nombre: "TUDN", url: "http://tv.teleclub.xyz/stream/server_2/deportes/tudn/master.m3u8" },
    { name: "tycsports", logo: "https://img.teleclub.xyz/tycsports.png", tipo: "deportes", nombre: "TyC Sports", url: "http://tv.teleclub.xyz/stream/server_2/deportes/tycsports/master.m3u8" },
    { name: "winsportsplus", logo: "https://img.teleclub.xyz/winsportsplus.png", tipo: "deportes", nombre: "Win Sports Plus", url: "http://tv.teleclub.xyz/stream/server_2/deportes/winsportsplus/master.m3u8" },
    { name: "cartoonnetwork", logo: "http://img.teleclub.xyz/cartoonnetwork.png", tipo: "infantiles", nombre: "Cartoon Network", url: "http://tv.teleclub.xyz/stream/server_3/infantil/cartoonnetwork/master.m3u8" },
    { name: "cartoonnetwork", logo: "http://img.teleclub.xyz/cartoonnetwork.png", tipo: "infantiles", nombre: "Cartoon Network", url: "http://tv.teleclub.xyz/stream/server_1/infantil/cartoonnetwork/master.m3u8" },
    { name: "cartoonito", logo: "http://img.teleclub.xyz/cartoonito.png", tipo: "infantiles", nombre: "Cartoonito", url: "http://tv.teleclub.xyz/stream/server_1/infantil/cartoonito/master.m3u8" },
    { name: "discoverykids", logo: "http://img.teleclub.xyz/discoverykids.png", tipo: "infantiles", nombre: "Discovery Kids", url: "http://tv.teleclub.xyz/stream/server_1/infantil/discoverykids/master.m3u8" },
    { name: "disney_channel", logo: "http://img.teleclub.xyz/disneychannel.png", tipo: "infantiles", nombre: "Disney Channel", url: "http://tv.teleclub.xyz/stream/server_1/infantil/disney_channel/master.m3u8" },
    { name: "disney_jr", logo: "http://img.teleclub.xyz/disneyjr.png", tipo: "infantiles", nombre: "Disney Jr", url: "http://tv.teleclub.xyz/stream/server_1/infantil/disney_jr/master.m3u8" },
    { name: "energeek_retro", logo: "https://energeek.cl/wp-content/uploads/2024/10/energeekstream.png", tipo: "infantiles", nombre: "Energeek Retro", url: "http://tv.teleclub.xyz/stream/server_0/infantil/energeek_retro/master.m3u8" },
    { name: "nick", logo: "http://img.teleclub.xyz/nick.png", tipo: "infantiles", nombre: "Nick", url: "http://tv.teleclub.xyz/stream/server_1/infantil/nick/master.m3u8" },
    { name: "tooncast", logo: "http://img.teleclub.xyz/tooncast.png", tipo: "infantiles", nombre: "Tooncast", url: "http://tv.teleclub.xyz/stream/server_1/infantil/tooncast/master.m3u8" },
    { name: "atv", logo: "https://img.teleclub.xyz/atvl.png", tipo: "variados", nombre: "ATV", url: "http://tv.teleclub.xyz/stream/server_1/mundo/atv/master.m3u8" },
    { name: "azteca7", logo: "https://img.teleclub.xyz/azteca7.png", tipo: "variados", nombre: "Azteca 7", url: "http://tv.teleclub.xyz/stream/server_1/mundo/azteca7/master.m3u8" },
    { name: "aztecauno", logo: "https://img.teleclub.xyz/azteca1.png", tipo: "variados", nombre: "Azteca Uno", url: "http://tv.teleclub.xyz/stream/server_1/mundo/aztecauno/master.m3u8" },
    { name: "canal5", logo: "https://img.teleclub.xyz/canal5.png", tipo: "variados", nombre: "Canal 5", url: "http://tv.teleclub.xyz/stream/server_1/mundo/canal5/master.m3u8" },
    { name: "canal_e", logo: "https://img.teleclub.xyz/canale.png", tipo: "variados", nombre: "Canal E!", url: "http://tv.teleclub.xyz/stream/server_1/mundo/canal_e/master.m3u8" },
    { name: "caracol", logo: "http://img.teleclub.xyz/caracol.png", tipo: "variados", nombre: "Caracol TV", url: "http://tv.teleclub.xyz/stream/server_1/mundo/caracol/master.m3u8" },
    { name: "cnnenespanol", logo: "https://img.teleclub.xyz/cnn.png", tipo: "variados", nombre: "CNN en Español", url: "http://tv.teleclub.xyz/stream/server_1/mundo/cnnenespanol/master.m3u8" },
    { name: "dwchannel", logo: "https://img.teleclub.xyz/dwchannel.png", tipo: "variados", nombre: "DW Channel", url: "http://tv.teleclub.xyz/stream/server_1/mundo/dwchannel/master.m3u8" },
    { name: "ecuavisa", logo: "https://img.teleclub.xyz/ecuavisa.png", tipo: "variados", nombre: "Ecuavisa", url: "http://tv.teleclub.xyz/stream/server_1/mundo/ecuavisa/master.m3u8" },
    { name: "eltrece", logo: "http://img.teleclub.xyz/trecel.png", tipo: "variados", nombre: "El Trece", url: "http://tv.teleclub.xyz/stream/server_1/mundo/eltrece/master.m3u8" },
    { name: "galavision", logo: "https://img.teleclub.xyz/galavson.png", tipo: "variados", nombre: "Galavision", url: "http://tv.teleclub.xyz/stream/server_1/mundo/galavision/master.m3u8" },
    { name: "imagenmx", logo: "https://img.teleclub.xyz/imagentv.png", tipo: "variados", nombre: "Imagen TV", url: "http://tv.teleclub.xyz/stream/server_1/mundo/imagenmx/master.m3u8" },
    { name: "lasestrellas", logo: "https://img.teleclub.xyz/lasestrellas.png", tipo: "variados", nombre: "Las Estrellas", url: "http://tv.teleclub.xyz/stream/server_1/mundo/lasestrellas/master.m3u8" },
    { name: "latina", logo: "http://img.teleclub.xyz/latinatv.png", tipo: "variados", nombre: "Latina TV", url: "http://tv.teleclub.xyz/stream/server_1/mundo/latina/master.m3u8" },
    { name: "pasiones", logo: "http://img.teleclub.xyz/pasiones.png", tipo: "variados", nombre: "Pasiones", url: "http://tv.teleclub.xyz/stream/server_1/mundo/pasiones/master.m3u8" },
    { name: "rcn", logo: "http://img.teleclub.xyz/rcn.png", tipo: "variados", nombre: "RCN", url: "http://tv.teleclub.xyz/stream/server_1/mundo/rcn/master.m3u8" },
    { name: "rcn", logo: "http://img.teleclub.xyz/rcn.png", tipo: "variados", nombre: "RCN", url: "http://tv.teleclub.xyz/stream/server_3/mundo/rcn/master.m3u8" },
    { name: "telefe", logo: "http://img.teleclub.xyz/telefe.png", tipo: "variados", nombre: "Telefe", url: "http://tv.teleclub.xyz/stream/server_1/mundo/telefe/master.m3u8" },
    { name: "telemundopuertorico", logo: "http://img.teleclub.xyz/telemundo.png", tipo: "variados", nombre: "Telemundo Puerto Rico", url: "http://tv.teleclub.xyz/stream/server_1/mundo/telemundopuertorico/master.m3u8" },
    { name: "tlc", logo: "https://img.teleclub.xyz/tlc.png", tipo: "variados", nombre: "TLC", url: "http://tv.teleclub.xyz/stream/server_1/mundo/tlc/master.m3u8" },
    { name: "tlnovelas", logo: "https://img.teleclub.xyz/tlnovelas.png", tipo: "variados", nombre: "tlnovelas", url: "http://tv.teleclub.xyz/stream/server_1/mundo/tlnovelas/master.m3u8" },
    { name: "tlnovelas", logo: "https://img.teleclub.xyz/tlnovelas.png", tipo: "variados", nombre: "tlnovelas", url: "http://tv.teleclub.xyz/stream/server_3/mundo/tlnovelas/master.m3u8" },
    { name: "unicable", logo: "https://img.teleclub.xyz/unicable.png", tipo: "variados", nombre: "Unicable", url: "http://tv.teleclub.xyz/stream/server_1/mundo/unicable/master.m3u8" },
    { name: "univision", logo: "http://img.teleclub.xyz/univision.png", tipo: "variados", nombre: "Univision", url: "http://tv.teleclub.xyz/stream/server_1/mundo/univision/master.m3u8" },
    { name: "willaxtv", logo: "https://img.teleclub.xyz/willaxtv.png", tipo: "variados", nombre: "Willax TV", url: "http://tv.teleclub.xyz/stream/server_1/mundo/willaxtv/master.m3u8" },
    { name: "animalplanet", logo: "https://img.teleclub.xyz/animalplanet.png", tipo: "variados", nombre: "Animal Planet", url: "http://tv.teleclub.xyz/stream/server_1/cultura/animalplanet/master.m3u8" },
    { name: "discoverychannel", logo: "https://img.teleclub.xyz/discoverychannel.png", tipo: "variados", nombre: "Discovery Channel", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoverychannel/master.m3u8" },
    { name: "discoveryh_h", logo: "https://img.teleclub.xyz/discoveryhh.png", tipo: "variados", nombre: "Discovery H&H", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoveryh_h/master.m3u8" },
    { name: "discoveryscience", logo: "https://img.teleclub.xyz/discoverysci.png", tipo: "variados", nombre: "Discovery Science", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoveryscience/master.m3u8" },
    { name: "discoverytheater", logo: "https://img.teleclub.xyz/discoverytheater.png", tipo: "variados", nombre: "Discovery Theater", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoverytheater/master.m3u8" },
    { name: "discoveryturbo", logo: "https://img.teleclub.xyz/discoveryturbo.png", tipo: "variados", nombre: "Discovery Turbo", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoveryturbo/master.m3u8" },
    { name: "discoveryworld", logo: "https://img.teleclub.xyz/discoveryworld.png", tipo: "variados", nombre: "Discovery World", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoveryworld/master.m3u8" },
    { name: "elgourmet", logo: "https://img.teleclub.xyz/elgourmet.png", tipo: "variados", nombre: "El Gourmet", url: "http://tv.teleclub.xyz/stream/server_1/cultura/elgourmet/master.m3u8" },
    { name: "h2", logo: "https://img.teleclub.xyz/h2.png", tipo: "variados", nombre: "H2", url: "http://tv.teleclub.xyz/stream/server_1/cultura/h2/master.m3u8" },
    { name: "history", logo: "https://img.teleclub.xyz/history.png", tipo: "variados", nombre: "History", url: "http://tv.teleclub.xyz/stream/server_3/cultura/history/master.m3u8" },
    { name: "history", logo: "https://img.teleclub.xyz/history.png", tipo: "variados", nombre: "History", url: "http://tv.teleclub.xyz/stream/server_1/cultura/history/master.m3u8" },
    { name: "discoveryid", logo: "https://img.teleclub.xyz/did.png", tipo: "variados", nombre: "ID", url: "http://tv.teleclub.xyz/stream/server_1/cultura/discoveryid/master.m3u8" },
    { name: "nationalgeographic", logo: "https://img.teleclub.xyz/natgeo.png", tipo: "variados", nombre: "National Geographic", url: "http://tv.teleclub.xyz/stream/server_1/cultura/nationalgeographic/master.m3u8" },
    { name: "a_e", logo: "https://img.teleclub.xyz/ae.png", tipo: "premium", nombre: "A&E", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/a_e/master.m3u8" },
    { name: "amc", logo: "https://img.teleclub.xyz/amc.png", tipo: "premium", nombre: "AMC", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/amc/master.m3u8" },
    { name: "antena3series", logo: "https://img.teleclub.xyz/antena3.png", tipo: "premium", nombre: "Antena 3 Series", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/antena3series/master.m3u8" },
    { name: "axn", logo: "https://img.teleclub.xyz/axn.png", tipo: "premium", nombre: "AXN", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/axn/master.m3u8" },
    { name: "axn", logo: "https://img.teleclub.xyz/axn.png", tipo: "premium", nombre: "AXN", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/axn/master.m3u8" },
    { name: "cinecanal", logo: "https://img.teleclub.xyz/cinecanal.png", tipo: "premium", nombre: "Cinecanal", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/cinecanal/master.m3u8" },
    { name: "cinecanal", logo: "https://img.teleclub.xyz/cinecanal.png", tipo: "premium", nombre: "Cinecanal", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/cinecanal/master.m3u8" },
    { name: "cinemax", logo: "https://img.teleclub.xyz/cinemax.png", tipo: "premium", nombre: "Cinemax", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/cinemax/master.m3u8" },
    { name: "comedycentral", logo: "https://img.teleclub.xyz/comedycentral.png", tipo: "premium", nombre: "Comedy Central", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/comedycentral/master.m3u8" },
    { name: "depelicula", logo: "https://img.teleclub.xyz/depelicula.png", tipo: "premium", nombre: "DePelicula", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/depelicula/master.m3u8" },
    { name: "dhe", logo: "https://img.teleclub.xyz/dhe.png", tipo: "premium", nombre: "DHE", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/dhe/master.m3u8" },
    { name: "distritocomedia", logo: "https://img.teleclub.xyz/distritocomedia.png", tipo: "premium", nombre: "Distrito Comedia", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/distritocomedia/master.m3u8" },
    { name: "fx", logo: "https://img.teleclub.xyz/fx.png", tipo: "premium", nombre: "FX", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/fx/master.m3u8" },
    { name: "fx", logo: "https://img.teleclub.xyz/fx.png", tipo: "premium", nombre: "FX", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/fx/master.m3u8" },
    { name: "golden", logo: "https://img.teleclub.xyz/golden.png", tipo: "premium", nombre: "Golden", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/golden/master.m3u8" },
    { name: "golden", logo: "https://img.teleclub.xyz/golden.png", tipo: "premium", nombre: "Golden", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/golden/master.m3u8" },
    { name: "goldenedge", logo: "https://img.teleclub.xyz/goldenedge.png", tipo: "premium", nombre: "Golden Edge", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenedge/master.m3u8" },
    { name: "goldenplus", logo: "https://img.teleclub.xyz/golden.png", tipo: "premium", nombre: "Golden Plus", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenplus/master.m3u8" },
    { name: "goldenpremier", logo: "https://img.teleclub.xyz/golden.png", tipo: "premium", nombre: "Golden Premier", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenpremier/master.m3u8" },
    { name: "goldenpremier", logo: "https://img.teleclub.xyz/golden.png", tipo: "premium", nombre: "Golden Premier", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/goldenpremier/master.m3u8" },
    { name: "goldenpremier2", logo: "https://img.teleclub.xyz/golden.png", tipo: "premium", nombre: "Golden Premier 2", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenpremier2/master.m3u8" },
    { name: "HBO", logo: "https://img.teleclub.xyz/hbo.png", tipo: "premium", nombre: "HBO", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/HBO/master.m3u8" },
    { name: "hbo", logo: "https://img.teleclub.xyz/hbo.png", tipo: "premium", nombre: "HBO", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/hbo/master.m3u8" },
    { name: "hbo2", logo: "https://img.teleclub.xyz/hbo2.png", tipo: "premium", nombre: "HBO 2", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/hbo2/master.m3u8" },
    { name: "hbofamily", logo: "https://img.teleclub.xyz/hbofamily.png", tipo: "premium", nombre: "HBO Family", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/hbofamily/master.m3u8" },
    { name: "hbo_family", logo: "https://img.teleclub.xyz/hbofamily.png", tipo: "premium", nombre: "HBO Family", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/hbo_family/master.m3u8" },
    { name: "hbomundi", logo: "https://img.teleclub.xyz/hbomundi.png", tipo: "premium", nombre: "HBO Mundi", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/hbomundi/master.m3u8" },
    { name: "hboplus", logo: "https://img.teleclub.xyz/hboplus.png", tipo: "premium", nombre: "HBO Plus", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/hboplus/master.m3u8" },
    { name: "hbopop", logo: "https://img.teleclub.xyz/hbopop.png", tipo: "premium", nombre: "HBO Pop", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/hbopop/master.m3u8" },
    { name: "hbosignature", logo: "https://raw.githubusercontent.com/deswes2021/westv/main/image/hbosignature.jpg", tipo: "premium", nombre: "HBO Signature", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/hbosignature/master.m3u8" },
    { name: "hboxtreme", logo: "https://img.teleclub.xyz/hboxtreme.png", tipo: "premium", nombre: "HBO Xtreme", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/hboxtreme/master.m3u8" },
    { name: "hboxtreme", logo: "https://img.teleclub.xyz/hboxtreme.png", tipo: "premium", nombre: "HBO Xtreme", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/hboxtreme/master.m3u8" },
    { name: "multipremier", logo: "https://img.teleclub.xyz/multipremier.png", tipo: "premium", nombre: "Multipremier", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/multipremier/master.m3u8" },
    { name: "paramountnetwork", logo: "https://img.teleclub.xyz/paramount.png", tipo: "premium", nombre: "Paramount Network", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/paramountnetwork/master.m3u8" },
    { name: "sony", logo: "https://img.teleclub.xyz/sony.png", tipo: "premium", nombre: "Sony", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/sony/master.m3u8" },
    { name: "sony", logo: "https://img.teleclub.xyz/sony.png", tipo: "premium", nombre: "Sony", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/sony/master.m3u8" },
    { name: "space", logo: "https://img.teleclub.xyz/space.png", tipo: "premium", nombre: "Space", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/space/master.m3u8" },
    { name: "space", logo: "https://img.teleclub.xyz/space.png", tipo: "premium", nombre: "Space", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/space/master.m3u8" },
    { name: "staraction", logo: "https://img.teleclub.xyz/staraction.png", tipo: "premium", nombre: "Star Action", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/staraction/master.m3u8" },
    { name: "starchannel", logo: "https://img.teleclub.xyz/star.png", tipo: "premium", nombre: "Star Channel", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/starchannel/master.m3u8" },
    { name: "starchannel", logo: "https://img.teleclub.xyz/star.png", tipo: "premium", nombre: "Star Channel", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/starchannel/master.m3u8" },
    { name: "starseries", logo: "https://img.teleclub.xyz/starseries.png", tipo: "premium", nombre: "Star Series", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/starseries/master.m3u8" },
    { name: "studiouniversal", logo: "https://img.teleclub.xyz/studiouniversal.png", tipo: "premium", nombre: "Studio Universal", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/studiouniversal/master.m3u8" },
    { name: "studiouniversal", logo: "https://img.teleclub.xyz/studiouniversal.png", tipo: "premium", nombre: "Studio Universasl", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/studiouniversal/master.m3u8" },
    { name: "tnt", logo: "https://img.teleclub.xyz/tnt.png", tipo: "premium", nombre: "TNT", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/tnt/master.m3u8" },
    { name: "tntseries", logo: "https://img.teleclub.xyz/tntseries.png", tipo: "premium", nombre: "TNT Series", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/tntseries/master.m3u8" },
    { name: "tntseries", logo: "https://img.teleclub.xyz/tntseries.png", tipo: "premium", nombre: "TNT Series", url: "http://tv.teleclub.xyz/stream/server_2/entretenimiento/tntseries/master.m3u8" },
    { name: "universalcinema", logo: "https://img.teleclub.xyz/universal_cinema.png", tipo: "premium", nombre: "Universal Cinema", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/universalcinema/master.m3u8" },
    { name: "universaltv", logo: "https://img.teleclub.xyz/universal.png", tipo: "premium", nombre: "Universal TV", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/universaltv/master.m3u8" },
    { name: "universaltv", logo: "https://img.teleclub.xyz/universal.png", tipo: "premium", nombre: "Universal TV", url: "http://tv.teleclub.xyz/stream/server_3/entretenimiento/universaltv/master.m3u8" },
    { name: "usatv", logo: "https://img.teleclub.xyz/usatv.png", tipo: "premium", nombre: "USA TV", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/usatv/master.m3u8" },
    { name: "warnerchannel", logo: "https://img.teleclub.xyz/warnerchannel.png", tipo: "premium", nombre: "Warner Channel", url: "http://tv.teleclub.xyz/stream/server_1/entretenimiento/warnerchannel/master.m3u8" },
    { name: "htv", logo: "https://img.teleclub.xyz/htv.png", tipo: "musica", nombre: "HTV", url: "http://tv.teleclub.xyz/stream/server_1/musica/htv/master.m3u8" },
    { name: "mtv", logo: "https://img.teleclub.xyz/mtv.png", tipo: "musica", nombre: "mtv", url: "http://tv.teleclub.xyz/stream/server_1/musica/mtv/master.m3u8" },
    { name: "mtvhits", logo: "https://img.teleclub.xyz/mtvhits.png", tipo: "musica", nombre: "MTV Hits", url: "http://tv.teleclub.xyz/stream/server_1/musica/mtvhits/master.m3u8" },
    { name: "musictop", logo: "https://img.teleclub.xyz/musictop.png", tipo: "musica", nombre: "Music Top", url: "http://tv.teleclub.xyz/stream/server_1/musica/musictop/master.m3u8" },
    { name: "telehit", logo: "https://img.teleclub.xyz/telehit.png", tipo: "musica", nombre: "Telehit", url: "http://tv.teleclub.xyz/stream/server_1/musica/telehit/master.m3u8" },
    { name: "toplatino", logo: "https://img.teleclub.xyz/toplatino.png", tipo: "musica", nombre: "Top Latino", url: "http://tv.teleclub.xyz/stream/server_1/musica/toplatino/master.m3u8" },
    { name: "ben10", logo: "https://img.teleclub.xyz/ben10.png", tipo: "247", nombre: "Ben 10", url: "http://tv.teleclub.xyz/stream/server_1/24x7/ben10/master.m3u8" },
    { name: "bobesponja", logo: "https://img.teleclub.xyz/bobesponja.png", tipo: "247", nombre: "Bob Esponja", url: "http://tv.teleclub.xyz/stream/server_1/24x7/bobesponja/master.m3u8" },
    { name: "casocerrado", logo: "https://img.teleclub.xyz/casocerrado.png", tipo: "247", nombre: "Caso Cerrado", url: "http://tv.teleclub.xyz/stream/server_1/24x7/casocerrado/master.m3u8" },
    { name: "chapulincolorado", logo: "https://img.teleclub.xyz/chapulincolorado.png", tipo: "247", nombre: "Chapulin Colorado", url: "http://tv.teleclub.xyz/stream/server_1/24x7/chapulincolorado/master.m3u8" },
    { name: "chespirito", logo: "https://img.teleclub.xyz/chespirito.png", tipo: "247", nombre: "Chespirito", url: "http://tv.teleclub.xyz/stream/server_1/24x7/chespirito/master.m3u8" },
    { name: "correcaminos", logo: "https://img.teleclub.xyz/correcaminos.png", tipo: "247", nombre: "Correcaminos", url: "http://tv.teleclub.xyz/stream/server_1/24x7/correcaminos/master.m3u8" },
    { name: "dinosaurios", logo: "https://img.teleclub.xyz/dinosaurios.png", tipo: "247", nombre: "Dinosaurios", url: "http://tv.teleclub.xyz/stream/server_1/24x7/dinosaurios/master.m3u8" },
    { name: "dragonballsuper", logo: "https://img.teleclub.xyz/dragonballsuper.png", tipo: "247", nombre: "Dragon Ball Super", url: "http://tv.teleclub.xyz/stream/server_1/24x7/dragonballsuper/master.m3u8" },
    { name: "elprincipedelrap", logo: "https://img.teleclub.xyz/elprincipedelrap.png", tipo: "247", nombre: "El principe del rap", url: "http://tv.teleclub.xyz/stream/server_1/24x7/elprincipedelrap/master.m3u8" },
    { name: "familiapeluche", logo: "https://img.teleclub.xyz/familiapeluche.png", tipo: "247", nombre: "Familia Peluche", url: "http://tv.teleclub.xyz/stream/server_1/24x7/familiapeluche/master.m3u8" },
    { name: "lospicapiedras", logo: "https://img.teleclub.xyz/lospicapiedras.png", tipo: "247", nombre: "Los Picapiedras", url: "http://tv.teleclub.xyz/stream/server_1/24x7/lospicapiedras/master.m3u8" },
    { name: "lossimpsons", logo: "https://img.teleclub.xyz/lossimpsons.png", tipo: "247", nombre: "Los Simpsons", url: "http://tv.teleclub.xyz/stream/server_1/24x7/lossimpsons/master.m3u8" },
    { name: "padrinosmagicos", logo: "https://img.teleclub.xyz/padrinosmagicos.png", tipo: "247", nombre: "Padrinos Magicos", url: "http://tv.teleclub.xyz/stream/server_1/24x7/padrinosmagicos/master.m3u8" },
    { name: "southpark", logo: "https://img.teleclub.xyz/southpark.png", tipo: "247", nombre: "South Park", url: "http://tv.teleclub.xyz/stream/server_1/24x7/southpark/master.m3u8" }
]
