[
    /*--MENUS--*/
    {
        tipo:'menu',
        logo:'herramientas.jpg',
        url:'herramientas',
    },
    {
        tipo:'menu',
        logo:'nacionales.jpg',
        url:'nacionales',
    },
    {
        tipo:'menu',
        logo:'infantiles.jpg',
        url:'infantiles',
    },
    {
        tipo:'menu',
        logo:'variados.jpg',
        url:'variados',
    },
    {
        tipo:'menu',
        logo:'premiums.jpg',
        url:'premiums',
    },
    {
        tipo:'menu',
        logo:'deportes.jpg',
        url:'deportes',
    },
    {
        tipo:'menu',
        logo:'moviefamiliar.jpg',
        url:'moviefamiliar',
    },
    {
        tipo:'menu',
        logo:'movieanime.jpg',
        url:'movieanime',
    },
    {
        tipo:'menu',
        logo:'moviewestern.jpg.',
        url:'moviewestern',
    },
    {
        tipo:'menu',
        logo:'moviefantasia.jpg.',
        url:'moviefantasia',
    },
    {
        tipo:'menu',
        logo:'movieaccion.jpg.',
        url:'movieaccion',
    },
    {
        tipo:'menu',
        logo:'movieterror.jpg.',
        url:'movieterror',
    },
      /*--MENUS--*/
]
