[
    /*--MENUS--*/
    {
        tipo:'menu',
        logo:'',
        url:'nacional',
    },
    {
        tipo:'menu',
        logo:'',
        url:'infantil',
    },
    {
        tipo:'menu',
        logo:'',
        url:'variado',
    },
    {
        tipo:'menu',
        logo:'',
        url:'premium',
    },    
    {
        tipo:'menu',
        logo:'',
        url:'opciones',
    },
    {
        tipo:'menu',
        logo:'',
        url:'deportes',
    },
    {
        tipo:'menu',
        logo:'',
        url:'peliculas',
    },
    {
        tipo:'menu',
        logo:'',
        url:'247',
    },
    {
        tipo:'menu',
        logo:'',
        url:'musica',
    },    
    /*--MENUS--*/
]
