#EXTINF: nombre="herr" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/herr.jpg" tipo="menu" url="herr"
#EXTINF: nombre="nacionales" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/nacionales.jpg" tipo="menu" url="nacionales"
#EXTINF: nombre="infantiles" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/infantiles.jpg" tipo="menu" url="infantiles"
#EXTINF: nombre="variados" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/variados.jpg" tipo="menu" url="variados"
#EXTINF: nombre="premium" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/premium.jpg" tipo="menu" url="premium"
#EXTINF: nombre="deportes" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/deportes.jpg" tipo="menu" url="deportes"
#EXTINF: nombre="247" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/247.jpg" tipo="menu" url="247"
/*--nacionales--*/
#EXTINF: nombre="tcs+" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal1.jpg" tipo="nacional" url="000000000"
#EXTINF: nombre="canal2" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal2.jpg" tipo="nacional" url="000000000"
#EXTINF: nombre="canal3" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal3.jpg" tipo="nacional" url="000000000"
#EXTINF: nombre="canal4" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal4.jpg" tipo="nacional" url="000000000"
#EXTINF: nombre="canal5" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal5.jpg" tipo="nacional" url="000000000"
#EXTINF: nombre="canal6" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal6.jpg" tipo="nacional" url="000000000"
#EXTINF: nombre="canal9" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal9.jpg" tipo="nacional" url="000000000"
#EXTINF: nombre="canal11" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal11.jpg" tipo="nacional" url="000000000"
#EXTINF: nombre="canal12" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal12.jpg" tipo="nacional" url="000000000"
#EXTINF: nombre="canal19" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal19.jpg" tipo="nacional" url="000000000"
#EXTINF: nombre="canal21" logo="https://raw.githubusercontent.com/deswes2021/westv/main/image/canal21.jpg" tipo="nacional" url="000000000"
/*--teleclub--*/
/*--teleclub--*/
/*--teleclub--*/
#EXTINF: nombre="beinsportsextran_2" logo="https://img.teleclub.xyz/beinsportsn.png" tipo="Deportes", Bein Sports Extra Ñ url="http://tv.teleclub.xyz/stream/server_2/deportes/beinsportsextran/master.m3u8"
#EXTINF: nombre="directvsports_2" logo="https://img.teleclub.xyz/directvsports.png" tipo="Deportes", Directv Sports url="http://tv.teleclub.xyz/stream/server_2/deportes/directvsports/master.m3u8"
#EXTINF: nombre="directvsportsplus_2" logo="https://img.teleclub.xyz/directvsports.png" tipo="Deportes", Directv Sports + url="http://tv.teleclub.xyz/stream/server_2/deportes/directvsportsplus/master.m3u8"
#EXTINF: nombre="directvsports2_2" logo="https://img.teleclub.xyz/directvsports2.png" tipo="Deportes", Directv Sports 2 url="http://tv.teleclub.xyz/stream/server_2/deportes/directvsports2/master.m3u8"
#EXTINF: nombre="espn1_2" logo="https://img.teleclub.xyz/espn.png" tipo="Deportes", ESPN 1 url="http://tv.teleclub.xyz/stream/server_2/deportes/espn1/master.m3u8"
#EXTINF: nombre="espn2_2" logo="https://img.teleclub.xyz/espn2.png" tipo="Deportes", ESPN 2 url="http://tv.teleclub.xyz/stream/server_2/deportes/espn2/master.m3u8"
#EXTINF: nombre="espn3_2" logo="https://img.teleclub.xyz/espn3.png" tipo="Deportes", ESPN 3 url="http://tv.teleclub.xyz/stream/server_2/deportes/espn3/master.m3u8"
#EXTINF: nombre="espn4_2" logo="https://img.teleclub.xyz/espn4.png" tipo="Deportes", ESPN 4 url="http://tv.teleclub.xyz/stream/server_2/deportes/espn4/master.m3u8"
#EXTINF: nombre="espn5_2" logo="https://img.teleclub.xyz/espn.png" tipo="Deportes", ESPN 5 url="http://tv.teleclub.xyz/stream/server_2/deportes/espn5/master.m3u8"
#EXTINF: nombre="espnpremium_2" logo="https://img.teleclub.xyz/espnpremium.png" tipo="Deportes", ESPN Premium url="http://tv.teleclub.xyz/stream/server_2/deportes/espnpremium/master.m3u8"
#EXTINF: nombre="foxsports1_2" logo="https://img.teleclub.xyz/foxsports.png" tipo="Deportes", Fox Sports 1 url="http://tv.teleclub.xyz/stream/server_2/deportes/foxsports1/master.m3u8"
#EXTINF: nombre="foxsports1mx_2" logo="https://img.teleclub.xyz/foxsports.png" tipo="Deportes", Fox Sports 1 MX url="http://tv.teleclub.xyz/stream/server_2/deportes/foxsports1mx/master.m3u8"
#EXTINF: nombre="foxsports2_2" logo="https://img.teleclub.xyz/foxsports2.png" tipo="Deportes", Fox Sports 2 url="http://tv.teleclub.xyz/stream/server_2/deportes/foxsports2/master.m3u8"
#EXTINF: nombre="foxsports2mx_2" logo="https://img.teleclub.xyz/foxsports2.png" tipo="Deportes", Fox Sports 2 MX url="http://tv.teleclub.xyz/stream/server_2/deportes/foxsports2mx/master.m3u8"
#EXTINF: nombre="foxsports2mx_3" logo="https://img.teleclub.xyz/foxsports2.png" tipo="Deportes", Fox Sports 2 MX url="http://tv.teleclub.xyz/stream/server_3/deportes/foxsports2mx/master.m3u8"
#EXTINF: nombre="foxsports3_2" logo="https://img.teleclub.xyz/foxsports3.png" tipo="Deportes", Fox Sports 3 url="http://tv.teleclub.xyz/stream/server_2/deportes/foxsports3/master.m3u8"
#EXTINF: nombre="foxsports3mx_2" logo="https://img.teleclub.xyz/foxsports3.png" tipo="Deportes", Fox Sports 3 MX url="http://tv.teleclub.xyz/stream/server_2/deportes/foxsports3mx/master.m3u8"
#EXTINF: nombre="foxsportspremiummx_2" logo="https://img.teleclub.xyz/foxsportspremium.png" tipo="Deportes", Fox Sports Premium MX url="http://tv.teleclub.xyz/stream/server_2/deportes/foxsportspremiummx/master.m3u8"
#EXTINF: nombre="golperu_2" logo="https://img.teleclub.xyz/golperu.png" tipo="Deportes", Gol Peru url="http://tv.teleclub.xyz/stream/server_2/deportes/golperu/master.m3u8"
#EXTINF: nombre="goltv_2" logo="https://img.teleclub.xyz/goltv.png" tipo="Deportes", Gol TV url="http://tv.teleclub.xyz/stream/server_2/deportes/goltv/master.m3u8"
#EXTINF: nombre="nbatv_2" logo="https://img.teleclub.xyz/nba.png" tipo="Deportes", NBA TV url="http://tv.teleclub.xyz/stream/server_2/deportes/nbatv/master.m3u8"
#EXTINF: nombre="tntsports_2" logo="https://img.teleclub.xyz/tntsports.png" tipo="Deportes", TNT Sports url="http://tv.teleclub.xyz/stream/server_2/deportes/tntsports/master.m3u8"
#EXTINF: nombre="tudn_2" logo="https://img.teleclub.xyz/tudn.png" tipo="Deportes", TUDN url="http://tv.teleclub.xyz/stream/server_2/deportes/tudn/master.m3u8"
#EXTINF: nombre="tycsports_2" logo="https://img.teleclub.xyz/tycsports.png" tipo="Deportes", TyC Sports url="http://tv.teleclub.xyz/stream/server_2/deportes/tycsports/master.m3u8"
#EXTINF: nombre="winsportsplus_2" logo="https://img.teleclub.xyz/winsportsplus.png" tipo="Deportes", Win Sports Plus url="http://tv.teleclub.xyz/stream/server_2/deportes/winsportsplus/master.m3u8"
#EXTINF: nombre="cartoonnetwork_3" logo="http://img.teleclub.xyz/cartoonnetwork.png" tipo="Infantil", Cartoon Network url="http://tv.teleclub.xyz/stream/server_3/infantil/cartoonnetwork/master.m3u8"
#EXTINF: nombre="cartoonnetwork_1" logo="http://img.teleclub.xyz/cartoonnetwork.png" tipo="Infantil", Cartoon Network url="http://tv.teleclub.xyz/stream/server_1/infantil/cartoonnetwork/master.m3u8"
#EXTINF: nombre="cartoonito_1" logo="http://img.teleclub.xyz/cartoonito.png" tipo="Infantil", Cartoonito url="http://tv.teleclub.xyz/stream/server_1/infantil/cartoonito/master.m3u8"
#EXTINF: nombre="discoverykids_1" logo="http://img.teleclub.xyz/discoverykids.png" tipo="Infantil", Discovery Kids url="http://tv.teleclub.xyz/stream/server_1/infantil/discoverykids/master.m3u8"
#EXTINF: nombre="disney_channel_1" logo="http://img.teleclub.xyz/disneychannel.png" tipo="Infantil", Disney Channel url="http://tv.teleclub.xyz/stream/server_1/infantil/disney_channel/master.m3u8"
#EXTINF: nombre="disney_jr_1" logo="http://img.teleclub.xyz/disneyjr.png" tipo="Infantil", Disney Jr url="http://tv.teleclub.xyz/stream/server_1/infantil/disney_jr/master.m3u8"
#EXTINF: nombre="energeek_retro_0" logo="https://energeek.cl/wp-content/uploads/2024/10/energeekstream.png" tipo="Infantil", Energeek Retro url="http://tv.teleclub.xyz/stream/server_0/infantil/energeek_retro/master.m3u8"
#EXTINF: nombre="nick_1" logo="http://img.teleclub.xyz/nick.png" tipo="Infantil", Nick url="http://tv.teleclub.xyz/stream/server_1/infantil/nick/master.m3u8"
#EXTINF: nombre="tooncast_1" logo="http://img.teleclub.xyz/tooncast.png" tipo="Infantil", Tooncast url="http://tv.teleclub.xyz/stream/server_1/infantil/tooncast/master.m3u8"
#EXTINF: nombre="atv_1" logo="https://img.teleclub.xyz/atvl.png" tipo="Mundo", ATV url="http://tv.teleclub.xyz/stream/server_1/mundo/atv/master.m3u8"
#EXTINF: nombre="azteca7_1" logo="https://img.teleclub.xyz/azteca7.png" tipo="Mundo", Azteca 7 url="http://tv.teleclub.xyz/stream/server_1/mundo/azteca7/master.m3u8"
#EXTINF: nombre="aztecauno_1" logo="https://img.teleclub.xyz/azteca1.png" tipo="Mundo", Azteca Uno url="http://tv.teleclub.xyz/stream/server_1/mundo/aztecauno/master.m3u8"
#EXTINF: nombre="canal5_1" logo="https://img.teleclub.xyz/canal5.png" tipo="Mundo", Canal 5 url="http://tv.teleclub.xyz/stream/server_1/mundo/canal5/master.m3u8"
#EXTINF: nombre="canal_e_1" logo="https://img.teleclub.xyz/canale.png" tipo="Mundo", Canal E! url="http://tv.teleclub.xyz/stream/server_1/mundo/canal_e/master.m3u8"
#EXTINF: nombre="caracol_1" logo="http://img.teleclub.xyz/caracol.png" tipo="Mundo", Caracol TV url="http://tv.teleclub.xyz/stream/server_1/mundo/caracol/master.m3u8"
#EXTINF: nombre="cnnenespanol_1" logo="https://img.teleclub.xyz/cnn.png" tipo="Mundo", CNN en Español url="http://tv.teleclub.xyz/stream/server_1/mundo/cnnenespanol/master.m3u8"
#EXTINF: nombre="dwchannel_1" logo="https://img.teleclub.xyz/dwchannel.png" tipo="Mundo", DW Channel url="http://tv.teleclub.xyz/stream/server_1/mundo/dwchannel/master.m3u8"
#EXTINF: nombre="ecuavisa_1" logo="https://img.teleclub.xyz/ecuavisa.png" tipo="Mundo", Ecuavisa url="http://tv.teleclub.xyz/stream/server_1/mundo/ecuavisa/master.m3u8"
#EXTINF: nombre="eltrece_1" logo="http://img.teleclub.xyz/trecel.png" tipo="Mundo", El Trece url="http://tv.teleclub.xyz/stream/server_1/mundo/eltrece/master.m3u8"
#EXTINF: nombre="galavision_1" logo="https://img.teleclub.xyz/galavson.png" tipo="Mundo", Galavisión url="http://tv.teleclub.xyz/stream/server_1/mundo/galavision/master.m3u8"
#EXTINF: nombre="imagenmx_1" logo="https://img.teleclub.xyz/imagentv.png" tipo="Mundo", Imagen TV url="http://tv.teleclub.xyz/stream/server_1/mundo/imagenmx/master.m3u8"
#EXTINF: nombre="lasestrellas_1" logo="https://img.teleclub.xyz/lasestrellas.png" tipo="Mundo", Las Estrellas url="http://tv.teleclub.xyz/stream/server_1/mundo/lasestrellas/master.m3u8"
#EXTINF: nombre="latina_1" logo="http://img.teleclub.xyz/latinatv.png" tipo="Mundo", Latina TV url="http://tv.teleclub.xyz/stream/server_1/mundo/latina/master.m3u8"
#EXTINF: nombre="pasiones_1" logo="http://img.teleclub.xyz/pasiones.png" tipo="Mundo", Pasiones url="http://tv.teleclub.xyz/stream/server_1/mundo/pasiones/master.m3u8"
#EXTINF: nombre="rcn_1" logo="http://img.teleclub.xyz/rcn.png" tipo="Mundo", RCN url="http://tv.teleclub.xyz/stream/server_1/mundo/rcn/master.m3u8"
#EXTINF: nombre="rcn_3" logo="http://img.teleclub.xyz/rcn.png" tipo="Mundo", RCN url="http://tv.teleclub.xyz/stream/server_3/mundo/rcn/master.m3u8"
#EXTINF: nombre="telefe_1" logo="http://img.teleclub.xyz/telefe.png" tipo="Mundo", Telefe url="http://tv.teleclub.xyz/stream/server_1/mundo/telefe/master.m3u8"
#EXTINF: nombre="telemundopuertorico_1" logo="http://img.teleclub.xyz/telemundo.png" tipo="Mundo", Telemundo Puerto Rico url="http://tv.teleclub.xyz/stream/server_1/mundo/telemundopuertorico/master.m3u8"
#EXTINF: nombre="tlc_1" logo="https://img.teleclub.xyz/tlc.png" tipo="Mundo", TLC url="http://tv.teleclub.xyz/stream/server_1/mundo/tlc/master.m3u8"
#EXTINF: nombre="tlnovelas_1" logo="https://img.teleclub.xyz/tlnovelas.png" tipo="Mundo", tlnovelas url="http://tv.teleclub.xyz/stream/server_1/mundo/tlnovelas/master.m3u8"
#EXTINF: nombre="tlnovelas_3" logo="https://img.teleclub.xyz/tlnovelas.png" tipo="Mundo", tlnovelas url="http://tv.teleclub.xyz/stream/server_3/mundo/tlnovelas/master.m3u8"
#EXTINF: nombre="unicable_1" logo="https://img.teleclub.xyz/unicable.png" tipo="Mundo", Unicable url="http://tv.teleclub.xyz/stream/server_1/mundo/unicable/master.m3u8"
#EXTINF: nombre="univision_1" logo="http://img.teleclub.xyz/univision.png" tipo="Mundo", Univisión url="http://tv.teleclub.xyz/stream/server_1/mundo/univision/master.m3u8"
#EXTINF: nombre="willaxtv_1" logo="https://img.teleclub.xyz/willaxtv.png" tipo="Mundo", Willax TV url="http://tv.teleclub.xyz/stream/server_1/mundo/willaxtv/master.m3u8"
#EXTINF: nombre="animalplanet_1" logo="https://img.teleclub.xyz/animalplanet.png" tipo="Cultura", Animal Planet url="http://tv.teleclub.xyz/stream/server_1/cultura/animalplanet/master.m3u8"
#EXTINF: nombre="discoverychannel_1" logo="https://img.teleclub.xyz/discoverychannel.png" tipo="Cultura", Discovery Channel url="http://tv.teleclub.xyz/stream/server_1/cultura/discoverychannel/master.m3u8"
#EXTINF: nombre="discoveryh_h_1" logo="https://img.teleclub.xyz/discoveryhh.png" tipo="Cultura", Discovery H&H url="http://tv.teleclub.xyz/stream/server_1/cultura/discoveryh_h/master.m3u8"
#EXTINF: nombre="discoveryscience_1" logo="https://img.teleclub.xyz/discoverysci.png" tipo="Cultura", Discovery Science url="http://tv.teleclub.xyz/stream/server_1/cultura/discoveryscience/master.m3u8"
#EXTINF: nombre="discoverytheater_1" logo="https://img.teleclub.xyz/discoverytheater.png" tipo="Cultura", Discovery Theater url="http://tv.teleclub.xyz/stream/server_1/cultura/discoverytheater/master.m3u8"
#EXTINF: nombre="discoveryturbo_1" logo="https://img.teleclub.xyz/discoveryturbo.png" tipo="Cultura", Discovery Turbo url="http://tv.teleclub.xyz/stream/server_1/cultura/discoveryturbo/master.m3u8"
#EXTINF: nombre="discoveryworld_1" logo="https://img.teleclub.xyz/discoveryworld.png" tipo="Cultura", Discovery World url="http://tv.teleclub.xyz/stream/server_1/cultura/discoveryworld/master.m3u8"
#EXTINF: nombre="elgourmet_1" logo="https://img.teleclub.xyz/elgourmet.png" tipo="Cultura", El Gourmet url="http://tv.teleclub.xyz/stream/server_1/cultura/elgourmet/master.m3u8"
#EXTINF: nombre="h2_1" logo="https://img.teleclub.xyz/h2.png" tipo="Cultura", H2 url="http://tv.teleclub.xyz/stream/server_1/cultura/h2/master.m3u8"
#EXTINF: nombre="history_3" logo="https://img.teleclub.xyz/history.png" tipo="Cultura", History url="http://tv.teleclub.xyz/stream/server_3/cultura/history/master.m3u8"
#EXTINF: nombre="history_1" logo="https://img.teleclub.xyz/history.png" tipo="Cultura", History url="http://tv.teleclub.xyz/stream/server_1/cultura/history/master.m3u8"
#EXTINF: nombre="discoveryid_1" logo="https://img.teleclub.xyz/did.png" tipo="Cultura", ID url="http://tv.teleclub.xyz/stream/server_1/cultura/discoveryid/master.m3u8"
#EXTINF: nombre="nationalgeographic_1" logo="https://img.teleclub.xyz/natgeo.png" tipo="Cultura", National Geographic url="http://tv.teleclub.xyz/stream/server_1/cultura/nationalgeographic/master.m3u8"
#EXTINF: nombre="a_e_1" logo="https://img.teleclub.xyz/ae.png" tipo="Entretenimiento", A&E url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/a_e/master.m3u8"
#EXTINF: nombre="amc_1" logo="https://img.teleclub.xyz/amc.png" tipo="Entretenimiento", AMC url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/amc/master.m3u8"
#EXTINF: nombre="antena3series_1" logo="https://img.teleclub.xyz/antena3.png" tipo="Entretenimiento", Antena 3 Series url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/antena3series/master.m3u8"
#EXTINF: nombre="axn_3" logo="https://img.teleclub.xyz/axn.png" tipo="Entretenimiento", AXN url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/axn/master.m3u8"
#EXTINF: nombre="axn_1" logo="https://img.teleclub.xyz/axn.png" tipo="Entretenimiento", AXN url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/axn/master.m3u8"
#EXTINF: nombre="cinecanal_3" logo="https://img.teleclub.xyz/cinecanal.png" tipo="Entretenimiento", Cinecanal url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/cinecanal/master.m3u8"
#EXTINF: nombre="cinecanal_1" logo="https://img.teleclub.xyz/cinecanal.png" tipo="Entretenimiento", Cinecanal url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/cinecanal/master.m3u8"
#EXTINF: nombre="cinemax_1" logo="https://img.teleclub.xyz/cinemax.png" tipo="Entretenimiento", Cinemax url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/cinemax/master.m3u8"
#EXTINF: nombre="comedycentral_1" logo="https://img.teleclub.xyz/comedycentral.png" tipo="Entretenimiento", Comedy Central url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/comedycentral/master.m3u8"
#EXTINF: nombre="depelicula_1" logo="https://img.teleclub.xyz/depelicula.png" tipo="Entretenimiento", DePelicula url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/depelicula/master.m3u8"
#EXTINF: nombre="dhe_1" logo="https://img.teleclub.xyz/dhe.png" tipo="Entretenimiento", DHE url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/dhe/master.m3u8"
#EXTINF: nombre="distritocomedia_1" logo="https://img.teleclub.xyz/distritocomedia.png" tipo="Entretenimiento", Distrito Comedia url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/distritocomedia/master.m3u8"
#EXTINF: nombre="fx_1" logo="https://img.teleclub.xyz/fx.png" tipo="Entretenimiento", FX url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/fx/master.m3u8"
#EXTINF: nombre="fx_3" logo="https://img.teleclub.xyz/fx.png" tipo="Entretenimiento", FX url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/fx/master.m3u8"
#EXTINF: nombre="golden_3" logo="https://img.teleclub.xyz/golden.png" tipo="Entretenimiento", Golden url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/golden/master.m3u8"
#EXTINF: nombre="golden_1" logo="https://img.teleclub.xyz/golden.png" tipo="Entretenimiento", Golden url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/golden/master.m3u8"
#EXTINF: nombre="goldenedge_1" logo="https://img.teleclub.xyz/goldenedge.png" tipo="Entretenimiento", Golden Edge url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenedge/master.m3u8"
#EXTINF: nombre="goldenplus_1" logo="https://img.teleclub.xyz/golden.png" tipo="Entretenimiento", Golden Plus url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenplus/master.m3u8"
#EXTINF: nombre="goldenpremier_1" logo="https://img.teleclub.xyz/golden.png" tipo="Entretenimiento", Golden Premier url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenpremier/master.m3u8"
#EXTINF: nombre="goldenpremier_3" logo="https://img.teleclub.xyz/golden.png" tipo="Entretenimiento", Golden Premier url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/goldenpremier/master.m3u8"
#EXTINF: nombre="goldenpremier2_1" logo="https://img.teleclub.xyz/golden.png" tipo="Entretenimiento", Golden Premier 2 url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/goldenpremier2/master.m3u8"
#EXTINF: nombre="HBO_3" logo="https://img.teleclub.xyz/hbo.png" tipo="Entretenimiento", HBO url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/HBO/master.m3u8"
#EXTINF: nombre="hbo_1" logo="https://img.teleclub.xyz/hbo.png" tipo="Entretenimiento", HBO url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/hbo/master.m3u8"
#EXTINF: nombre="hbo2_1" logo="https://img.teleclub.xyz/hbo2.png" tipo="Entretenimiento", HBO 2 url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/hbo2/master.m3u8"
#EXTINF: nombre="hbofamily_1" logo="https://img.teleclub.xyz/hbofamily.png" tipo="Entretenimiento", HBO Family url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/hbofamily/master.m3u8"
#EXTINF: nombre="hbo_family_3" logo="https://img.teleclub.xyz/hbofamily.png" tipo="Entretenimiento", HBO Family url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/hbo_family/master.m3u8"
#EXTINF: nombre="hbomundi_1" logo="https://img.teleclub.xyz/hbomundi.png" tipo="Entretenimiento", HBO Mundi url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/hbomundi/master.m3u8"
#EXTINF: nombre="hboplus_1" logo="https://img.teleclub.xyz/hboplus.png" tipo="Entretenimiento", HBO Plus url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/hboplus/master.m3u8"
#EXTINF: nombre="hbopop_1" logo="https://img.teleclub.xyz/hbopop.png" tipo="Entretenimiento", HBO Pop url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/hbopop/master.m3u8"
#EXTINF: nombre="hbosignature_3" logo="" tipo="Entretenimiento", HBO Signature url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/hbosignature/master.m3u8"
#EXTINF: nombre="hboxtreme_3" logo="https://img.teleclub.xyz/hboxtreme.png" tipo="Entretenimiento", HBO Xtreme url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/hboxtreme/master.m3u8"
#EXTINF: nombre="hboxtreme_1" logo="https://img.teleclub.xyz/hboxtreme.png" tipo="Entretenimiento", HBO Xtreme url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/hboxtreme/master.m3u8"
#EXTINF: nombre="multipremier_1" logo="https://img.teleclub.xyz/multipremier.png" tipo="Entretenimiento", Multipremier url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/multipremier/master.m3u8"
#EXTINF: nombre="paramountnetwork_1" logo="https://img.teleclub.xyz/paramount.png" tipo="Entretenimiento", Paramount Network url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/paramountnetwork/master.m3u8"
#EXTINF: nombre="sony_1" logo="https://img.teleclub.xyz/sony.png" tipo="Entretenimiento", Sony url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/sony/master.m3u8"
#EXTINF: nombre="sony_3" logo="https://img.teleclub.xyz/sony.png" tipo="Entretenimiento", Sony url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/sony/master.m3u8"
#EXTINF: nombre="space_3" logo="https://img.teleclub.xyz/space.png" tipo="Entretenimiento", Space url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/space/master.m3u8"
#EXTINF: nombre="space_1" logo="https://img.teleclub.xyz/space.png" tipo="Entretenimiento", Space url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/space/master.m3u8"
#EXTINF: nombre="staraction_1" logo="https://img.teleclub.xyz/staraction.png" tipo="Entretenimiento", Star Action url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/staraction/master.m3u8"
#EXTINF: nombre="starchannel_1" logo="https://img.teleclub.xyz/star.png" tipo="Entretenimiento", Star Channel url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/starchannel/master.m3u8"
#EXTINF: nombre="starchannel_3" logo="https://img.teleclub.xyz/star.png" tipo="Entretenimiento", Star Channel url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/starchannel/master.m3u8"
#EXTINF: nombre="starseries_1" logo="https://img.teleclub.xyz/starseries.png" tipo="Entretenimiento", Star Series url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/starseries/master.m3u8"
#EXTINF: nombre="studiouniversal_3" logo="https://img.teleclub.xyz/studiouniversal.png" tipo="Entretenimiento", Studio Universal url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/studiouniversal/master.m3u8"
#EXTINF: nombre="studiouniversal_1" logo="https://img.teleclub.xyz/studiouniversal.png" tipo="Entretenimiento", Studio Universasl url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/studiouniversal/master.m3u8"
#EXTINF: nombre="tnt_1" logo="https://img.teleclub.xyz/tnt.png" tipo="Entretenimiento", TNT url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/tnt/master.m3u8"
#EXTINF: nombre="tntseries_1" logo="https://img.teleclub.xyz/tntseries.png" tipo="Entretenimiento", TNT Series url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/tntseries/master.m3u8"
#EXTINF: nombre="tntseries_2" logo="https://img.teleclub.xyz/tntseries.png" tipo="Entretenimiento", TNT Series url="http://tv.teleclub.xyz/stream/server_2/entretenimiento/tntseries/master.m3u8"
#EXTINF: nombre="universalcinema_1" logo="https://img.teleclub.xyz/universal_cinema.png" tipo="Entretenimiento", Universal Cinema url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/universalcinema/master.m3u8"
#EXTINF: nombre="universaltv_1" logo="https://img.teleclub.xyz/universal.png" tipo="Entretenimiento", Universal TV url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/universaltv/master.m3u8"
#EXTINF: nombre="universaltv_3" logo="https://img.teleclub.xyz/universal.png" tipo="Entretenimiento", Universal TV url="http://tv.teleclub.xyz/stream/server_3/entretenimiento/universaltv/master.m3u8"
#EXTINF: nombre="usatv_1" logo="https://img.teleclub.xyz/usatv.png" tipo="Entretenimiento", USA TV url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/usatv/master.m3u8"
#EXTINF: nombre="warnerchannel_1" logo="https://img.teleclub.xyz/warnerchannel.png" tipo="Entretenimiento", Warner Channel url="http://tv.teleclub.xyz/stream/server_1/entretenimiento/warnerchannel/master.m3u8"
#EXTINF: nombre="htv_1" logo="https://img.teleclub.xyz/htv.png" tipo="Musica", HTV url="http://tv.teleclub.xyz/stream/server_1/musica/htv/master.m3u8"
#EXTINF: nombre="mtv_1" logo="https://img.teleclub.xyz/mtv.png" tipo="Musica", mtv url="http://tv.teleclub.xyz/stream/server_1/musica/mtv/master.m3u8"
#EXTINF: nombre="mtvhits_1" logo="https://img.teleclub.xyz/mtvhits.png" tipo="Musica", MTV Hits url="http://tv.teleclub.xyz/stream/server_1/musica/mtvhits/master.m3u8"
#EXTINF: nombre="musictop_1" logo="https://img.teleclub.xyz/musictop.png" tipo="Musica", Music Top url="http://tv.teleclub.xyz/stream/server_1/musica/musictop/master.m3u8"
#EXTINF: nombre="telehit_1" logo="https://img.teleclub.xyz/telehit.png" tipo="Musica", Telehit url="http://tv.teleclub.xyz/stream/server_1/musica/telehit/master.m3u8"
#EXTINF: nombre="toplatino_1" logo="https://img.teleclub.xyz/toplatino.png" tipo="Musica", Top Latino url="http://tv.teleclub.xyz/stream/server_1/musica/toplatino/master.m3u8"
#EXTINF: nombre="ben10_1" logo="https://img.teleclub.xyz/ben10.png" tipo="24x7", Ben 10 url="http://tv.teleclub.xyz/stream/server_1/24x7/ben10/master.m3u8"
#EXTINF: nombre="bobesponja_1" logo="https://img.teleclub.xyz/bobesponja.png" tipo="24x7", Bob Esponja url="http://tv.teleclub.xyz/stream/server_1/24x7/bobesponja/master.m3u8"
#EXTINF: nombre="casocerrado_1" logo="https://img.teleclub.xyz/casocerrado.png" tipo="24x7", Caso Cerrado url="http://tv.teleclub.xyz/stream/server_1/24x7/casocerrado/master.m3u8"
#EXTINF: nombre="chapulincolorado_1" logo="https://img.teleclub.xyz/chapulincolorado.png" tipo="24x7", Chapulin Colorado url="http://tv.teleclub.xyz/stream/server_1/24x7/chapulincolorado/master.m3u8"
#EXTINF: nombre="chespirito_1" logo="https://img.teleclub.xyz/chespirito.png" tipo="24x7", Chespirito url="http://tv.teleclub.xyz/stream/server_1/24x7/chespirito/master.m3u8"
#EXTINF: nombre="correcaminos_1" logo="https://img.teleclub.xyz/correcaminos.png" tipo="24x7", Correcaminos url="http://tv.teleclub.xyz/stream/server_1/24x7/correcaminos/master.m3u8"
#EXTINF: nombre="dinosaurios_1" logo="https://img.teleclub.xyz/dinosaurios.png" tipo="24x7", Dinosaurios url="http://tv.teleclub.xyz/stream/server_1/24x7/dinosaurios/master.m3u8"
#EXTINF: nombre="dragonballsuper_1" logo="https://img.teleclub.xyz/dragonballsuper.png" tipo="24x7", Dragon Ball Super url="http://tv.teleclub.xyz/stream/server_1/24x7/dragonballsuper/master.m3u8"
#EXTINF: nombre="elprincipedelrap_1" logo="https://img.teleclub.xyz/elprincipedelrap.png" tipo="24x7", El príncipe del rap url="http://tv.teleclub.xyz/stream/server_1/24x7/elprincipedelrap/master.m3u8"
#EXTINF: nombre="familiapeluche_1" logo="https://img.teleclub.xyz/familiapeluche.png" tipo="24x7", Familia Peluche url="http://tv.teleclub.xyz/stream/server_1/24x7/familiapeluche/master.m3u8"
#EXTINF: nombre="lospicapiedras_1" logo="https://img.teleclub.xyz/lospicapiedras.png" tipo="24x7", Los Picapiedras url="http://tv.teleclub.xyz/stream/server_1/24x7/lospicapiedras/master.m3u8"
#EXTINF: nombre="lossimpsons_1" logo="https://img.teleclub.xyz/lossimpsons.png" tipo="24x7", Los Simpsons url="http://tv.teleclub.xyz/stream/server_1/24x7/lossimpsons/master.m3u8"
#EXTINF: nombre="padrinosmagicos_1" logo="https://img.teleclub.xyz/padrinosmagicos.png" tipo="24x7", Padrinos Magícos url="http://tv.teleclub.xyz/stream/server_1/24x7/padrinosmagicos/master.m3u8"
#EXTINF: nombre="southpark_1" logo="https://img.teleclub.xyz/southpark.png" tipo="24x7", South Park url="http://tv.teleclub.xyz/stream/server_1/24x7/southpark/master.m3u8"
